In [0]:
# Below are links to online materials 

https://www.kaggle.com/learn/python?utm_medium=social&utm_source=twitter.com&utm_campaign=new%20python%20course%20announcement

https://kantologist.github.io/Tutorials/#!/

https://docs.python.org/3/tutorial/index.html

https://www.geeksforgeeks.org/numpy-python-set-2-advanced/

http://cs231n.github.io/python-numpy-tutorial/

https://engineering.ucsb.edu/~shell/che210d/numpy.pdf

for our introduction to pandas:

https://colab.research.google.com/notebooks/mlcc/intro_to_pandas.ipynb

In [0]:
import pandas as pd

In [0]:
import numpy as np

In [0]:
import matplotlib.pyplot as plt

In [8]:
! python --version

Python 3.6.3


In [0]:
arr = np.array([[1, 2], [4, 5]])

In [0]:
b = arr[:1, :]

In [62]:
arr

array([[1, 2],
       [4, 5]])

In [66]:
b


array([[1, 2]])

In [0]:
c = np.multiply(arr, b)

In [13]:
print(c)

[[ 4  4  9]
 [16 35 36]]


In [0]:
c=np.multiply(arr,b)

In [15]:
c

array([[ 4,  4,  9],
       [16, 35, 36]])

In [16]:
print(c)

[[ 4  4  9]
 [16 35 36]]


In [19]:
multiplicands = (2, 2, 2, 3, 3, 5)
product = 2
for mult in multiplicands:
    product = product * mult
product

720

In [21]:
s = 'steganograpHy is the practicE of conceaLing a file, message, image, or video within another fiLe, message, image, Or video.'
msg = ''
# print all the uppercase letters in s, one at a time
for char in s:
    if char.islower():
        print(char, end=' ')  

s t e g a n o g r a p y i s t h e p r a c t i c o f c o n c e a i n g a f i l e m e s s a g e i m a g e o r v i d e o w i t h i n a n o t h e r f i e m e s s a g e i m a g e r v i d e o 

In [24]:
for i in range(2, 10, 2):
  print(i)

2
4
6
8


In [26]:
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |

In [0]:
x = ['a', 'b', 'c', 3]

In [28]:
a

['a', 'b', 'c', 3]

In [29]:
type(a)

list

In [34]:
x[0]

'a'

In [35]:
x[1]

'b'

In [36]:
x[:3]

['a', 'b', 'c']

In [37]:
x[:4]

['a', 'b', 'c', 3]

In [38]:
x[0:4]

['a', 'b', 'c', 3]

In [39]:
x[:]

['a', 'b', 'c', 3]

In [40]:
x[-1]

3

In [44]:
x[-4:-1]

['a', 'b', 'c']

In [46]:
x[-4:]

['a', 'b', 'c', 3]

In [51]:
name = 'Teju'
','.join(sorted(name.lower()))

'e,j,t,u'

In [0]:
a = np.array([[5, 6], [3, 4]])

In [68]:
a

array([[5, 6],
       [3, 4]])

In [71]:
a[0:, 0:1]

array([[5],
       [3]])

In [70]:
a[:, :]

array([[5, 6],
       [3, 4]])

In [75]:
a[0:, 1:]

array([[6],
       [4]])

In [76]:
a[1:, :]

array([[3, 4]])

In [77]:
a[1:, 0:1]

array([[3]])

In [78]:
a[1:, 1:]

array([[4]])

In [79]:
a[1:, :]

array([[3, 4]])

In [0]:
b = np.array([[1, 3], [2, 4]])

In [81]:
b


array([[1, 3],
       [2, 4]])

In [82]:
b[1:, :]

array([[2, 4]])

In [83]:
b[0:, :]

array([[1, 3],
       [2, 4]])

In [84]:
b[0:1, :]

array([[1, 3]])

In [85]:
b[:1, :]

array([[1, 3]])

In [86]:
b[0, 1]

3

In [87]:
b[0,0]

1

In [88]:
b[0, :]

array([1, 3])

In [0]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [90]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
b[0, :]

array([1, 2, 3])

In [92]:
b[:, 1:2]

array([[2],
       [5],
       [8]])

In [93]:
b[:, 1]

array([2, 5, 8])